puts "The students of Villains Academy"
puts "------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarte"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Jocker"
puts "Joffrey Baratheon"
puts "Norman Bates"
print "Overall we have "
print 11
puts " great students"
